# ----- List of lines with stations, transfer stations are considered to be a single station -----
vienna_ubahn_edges = {
    "U1": [
        ("Oberlaa", "Neulaa", 1.05),
        ("Neulaa", "Alaudagasse", 0.90),
        ("Alaudagasse", "Altes Landgut", 1.10),
        ("Altes Landgut", "Sportklub", 1.20),
        ("Sportklub", "Stadion", 0.85),
        ("Stadion", "Krieau", 0.70),
        ("Krieau", "Donaustadtbrücke", 0.95),
        ("Donaustadtbrücke", "Donauinsel", 0.80),
        ("Donauinsel", "Vorgartenstraße", 0.70),
        ("Vorgartenstraße", "Praterstern", 0.90),
        ("Praterstern", "Schwedenplatz", 0.55),
        ("Schwedenplatz", "Stephansplatz", 0.50),
        ("Stephansplatz", "Karlsplatz", 0.75),
        ("Karlsplatz", "Taubstummengasse", 0.85),
        ("Taubstummengasse", "Nestroyplatz", 0.60),
        ("Nestroyplatz", "Grossfeldsiedlung", 1.30),
        ("Grossfeldsiedlung", "Kagraner Platz", 0.90),
        ("Kagraner Platz", "Rennbahnweg", 1.10),
        ("Rennbahnweg", "Alte Donau", 0.95),
        ("Alte Donau", "Kaisermühlen", 0.85),
        ("Kaisermühlen", "Kagran", 1.15),
        ("Kagran", "Aderklaaer Straße", 1.20),
        ("Aderklaaer Straße", "Leopoldau", 1.25),
    ],
    "U2": [
        ("Karlsplatz", "Museumsquartier", 0.60),
        ("Museumsquartier", "Volkstheater", 0.35),
        ("Volkstheater", "Schottentor", 0.75),
        ("Schottentor", "Rathaus", 0.85),
        ("Rathaus", "Schottenring", 0.60),
        ("Schottenring", "Taborstraße", 1.10),
        ("Taborstraße", "Praterstern", 0.90),
        ("Praterstern", "Messe-Prater", 0.80),
        ("Messe-Prater", "Stadion", 0.65),
        ("Stadion", "Aspernstraße", 0.75),
        ("Aspernstraße", "Aspern Nord", 1.50),
        ("Aspern Nord", "Hausfeldstraße", 1.40),
        ("Hausfeldstraße", "Seestadt", 1.60),
    ],
    "U3": [
        ("Ottakring", "Kendlerstraße", 0.85),
        ("Kendlerstraße", "Schweglerstraße", 0.65),
        ("Schweglerstraße", "Johnstraße", 0.60),
        ("Johnstraße", "Zieglergasse", 0.70),
        ("Zieglergasse", "Westbahnhof", 1.10),
        ("Westbahnhof", "Neubaugasse", 0.75),
        ("Neubaugasse", "Volkstheater", 0.55),
        ("Volkstheater", "Stephansplatz", 0.70),
        ("Stephansplatz", "Herrengasse", 0.50),
        ("Herrengasse", "Stubentor", 0.60),
        ("Stubentor", "Landstraße", 0.80),
        ("Landstraße", "Rochusgasse", 0.75),
        ("Rochusgasse", "Kardinal-Nagl-Platz", 0.85),
        ("Kardinal-Nagl-Platz", "Schlachthausgasse", 0.90),
        ("Schlachthausgasse", "Zippererstraße", 1.10),
        ("Zippererstraße", "Gasometer", 1.00),
        ("Gasometer", "Enkplatz", 1.20),
        ("Enkplatz", "Simmering", 1.30),
    ],
    "U4": [
        ("Hütteldorf", "Ober St. Veit", 0.80),
        ("Ober St. Veit", "Unter St. Veit", 0.70),
        ("Unter St. Veit", "Braunschweiggasse", 0.90),
        ("Braunschweiggasse", "Hietzing", 0.75),
        ("Hietzing", "Schönbrunn", 0.85),
        ("Schönbrunn", "Meidling Hauptstraße", 1.00),
        ("Meidling Hauptstraße", "Längenfeldgasse", 1.05),
        ("Längenfeldgasse", "Margaretengürtel", 0.65),
        ("Margaretengürtel", "Kettenbrückengasse", 0.70),
        ("Kettenbrückengasse", "Karlsplatz", 0.80),
        ("Karlsplatz", "Stadtpark", 0.70),
        ("Stadtpark", "Landstraße", 0.60),
        ("Landstraße", "Schottenring", 0.85),
        ("Schottenring", "Schwedenplatz", 0.50),
        ("Schwedenplatz", "Friedensbrücke", 0.65),
        ("Friedensbrücke", "Roßauer Lände", 0.50),
        ("Roßauer Lände", "Spittelau", 0.85),
        ("Spittelau", "Heiligenstadt", 1.15),
    ],
    "U6": [
        ("Siebenhirten", "Erlaaer Straße", 0.90),
        ("Erlaaer Straße", "Perfektastraße", 0.75),
        ("Perfektastraße", "Am Schöpfwerk", 0.80),
        ("Am Schöpfwerk", "Tscherttegasse", 0.90),
        ("Tscherttegasse", "Niederhofstraße", 0.70),
        ("Niederhofstraße", "Bahnhof Meidling", 0.85),
        ("Bahnhof Meidling", "Längenfeldgasse", 0.80),
        ("Längenfeldgasse", "Gumpendorfer Straße", 1.00),
        ("Gumpendorfer Straße", "Westbahnhof", 1.10),
        ("Westbahnhof", "Burggasse-Stadthalle", 0.75),
        ("Burggasse-Stadthalle", "Thaliastraße", 0.60),
        ("Thaliastraße", "Josefstädter Straße", 0.65),
        ("Josefstädter Straße", "Alser Straße", 0.60),
        ("Alser Straße", "Michelbeuern-AKH", 0.75),
        ("Michelbeuern-AKH", "Währinger Straße-Volksoper", 0.70),
        ("Währinger Straße-Volksoper", "Nußdorfer Straße", 0.65),
        ("Nußdorfer Straße", "Spittelau", 0.85),
        ("Spittelau", "Jägerstraße", 0.80),
        ("Jägerstraße", "Dresdner Straße", 0.75),
        ("Dresdner Straße", "Handelskai", 0.80),
        ("Handelskai", "Neue Donau", 0.90),
        ("Neue Donau", "Floridsdorf", 1.10),
    ],
}
